name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # @v4.3.0
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 24.x
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run check:code
